# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import helpful.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='menu_groups', to='sites.Site', verbose_name='Sites'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='A slug is the part of a URL which identifies a page using human-readable keywords', max_length=128, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.ImageField(blank=True, upload_to=helpful.fields.upload_to, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='sites.Site', verbose_name='Sites'),
        ),
    ]
