# Generated by Django 2.0.4 on 2018-05-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0002_auto_20160621_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='access',
            field=models.CharField(choices=[('all', 'All'), ('anonymous_only', 'Anonymous only'), ('login_required', 'Login required'), ('exclude', 'Except'), ('filter', 'Only'), ('advanced_access', 'Advanced Access')], default='all', max_length=32, verbose_name='Access'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url_options',
            field=models.TextField(blank=True, help_text='key1=value1<br>key2=value2', verbose_name='URL Options'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url_type',
            field=models.CharField(choices=[('internal', (('model-oblect', 'model oblect'), ('url-patterns', 'url patterns'))), ('external', (('external', 'external'),))], max_length=20, verbose_name='URL Type'),
        ),
    ]
